Correctly include Go toolchain in all relevant helper images. (#264)

diff --git a/package-builders/Dockerfile.debian10.v1 b/package-builders/Dockerfile.debian10.v1
--- a/package-builders/Dockerfile.debian10.v1
+++ b/package-builders/Dockerfile.debian10.v1
@@ -33,7 +33,6 @@ RUN apt-get update && \
                        gcc \
                        git-buildpackage \
                        git-core \
-                       golang \
                        libatomic1 \
                        libcups2-dev \
                        libcurl4-openssl-dev \
@@ -75,6 +74,13 @@ RUN curl --fail -sSL --connect-timeout 10 --retry 3 https://sentry.io/get-cli/ >
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/debian-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
diff --git a/package-builders/Dockerfile.fedora37.v1 b/package-builders/Dockerfile.fedora37.v1
--- a/package-builders/Dockerfile.fedora37.v1
+++ b/package-builders/Dockerfile.fedora37.v1
@@ -28,7 +28,6 @@ RUN dnf distro-sync -y --nodocs && \
         gcc \
         gcc-c++ \
         git-core \
-        golang \
         json-c-devel \
         libcurl-devel \
         libyaml-devel \
@@ -67,6 +66,13 @@ RUN dnf distro-sync -y --nodocs && \
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/fedora-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
diff --git a/package-builders/Dockerfile.opensuse15.5.v1 b/package-builders/Dockerfile.opensuse15.5.v1
--- a/package-builders/Dockerfile.opensuse15.5.v1
+++ b/package-builders/Dockerfile.opensuse15.5.v1
@@ -25,7 +25,6 @@ RUN zypper update -y && \
                       gcc \
                       gcc-c++ \
                       git-core \
-                      go \
                       json-glib-devel \
                       judy-devel \
                       libatomic1 \
@@ -65,6 +64,13 @@ RUN zypper update -y && \
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/suse-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
diff --git a/package-builders/Dockerfile.rockylinux8.v1 b/package-builders/Dockerfile.rockylinux8.v1
--- a/package-builders/Dockerfile.rockylinux8.v1
+++ b/package-builders/Dockerfile.rockylinux8.v1
@@ -31,7 +31,6 @@ RUN dnf distro-sync -y --nodocs && \
         gcc \
         gcc-c++ \
         git \
-        golang \
         json-c-devel \
         libatomic \
         libmnl-devel \
@@ -73,6 +72,13 @@ RUN dnf distro-sync -y --nodocs && \
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/fedora-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
diff --git a/static-builder/Dockerfile.v1 b/static-builder/Dockerfile.v1
--- a/static-builder/Dockerfile.v1
+++ b/static-builder/Dockerfile.v1
@@ -56,3 +56,10 @@ RUN apk add --no-cache \
     zstd-static
 
 COPY static-builder/snappy.pc /usr/lib/pkgconfig/snappy.pc
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
