Correctly include Go toolchain in all relevant helper images.

diff --git a/builder/Dockerfile.v2 b/builder/Dockerfile.v2
--- a/builder/Dockerfile.v2
+++ b/builder/Dockerfile.v2
@@ -61,3 +61,10 @@ RUN chown _apt:root /var/cache/apt /var/lib/apt && \
     fi && \
     mkdir -p /deps/etc && \
     rm -rf /var/cache/apt/* /var/lib/apt/lists/*
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
diff --git a/package-builders/Dockerfile.centos7.v1 b/package-builders/Dockerfile.centos7.v1
--- a/package-builders/Dockerfile.centos7.v1
+++ b/package-builders/Dockerfile.centos7.v1
@@ -29,7 +29,6 @@ RUN yum install -y epel-release && \
                    gcc \
                    gcc-c++ \
                    git-core \
-                   golang \
                    json-c-devel \
                    libyaml-devel \
                    libatomic \
@@ -83,6 +82,13 @@ RUN curl --fail -sSL --connect-timeout 20 --retry 3 --output cmake-linux-$(uname
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/fedora-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
diff --git a/package-builders/Dockerfile.ubuntu23.04.v1 b/package-builders/Dockerfile.ubuntu23.04.v1
--- a/package-builders/Dockerfile.ubuntu23.04.v1
+++ b/package-builders/Dockerfile.ubuntu23.04.v1
@@ -32,7 +32,6 @@ RUN apt-get update && \
                        gcc \
                        git-buildpackage \
                        git-core \
-                       golang \
                        libatomic1 \
                        libcups2-dev \
                        libcurl4-openssl-dev \
@@ -70,6 +69,13 @@ RUN apt-get update && \
 
 COPY package-builders/entrypoint.sh /entrypoint.sh
 COPY package-builders/debian-build.sh /build.sh
+
+ENV PATH="/usr/local/go/bin:${PATH}"
+ADD https://raw.githubusercontent.com/netdata/netdata/master/packaging/check-for-go-toolchain.sh /tmp/check-for-go-toolchain.sh
+RUN . /tmp/check-for-go-toolchain.sh && \
+    if ! ensure_go_toolchain; then \
+        echo "ERROR: ${GOLANG_FAILURE_REASON}" && exit 1 ; \
+    fi
 
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["/build.sh"]
